src/Bennington.ContentTree.TreeManager/Models/TreeBranchViewModel.cs
using System;
using System.Collections.Generic;
using Bennington.ContentTree.Models;

namespace Bennington.ContentTree.TreeManager.Models
{
	public class TreeBranchViewModel
	{
        public IEnumerable<TreeBranchItemViewModel> TreeNodeSummaries { get; set; }
	}

    public class TreeBranchItemViewModel
    {
        public TreeNodeSummary TreeNodeSummary { get; set; }
    }
}

src/Bennington.ContentTree.TreeManager/Models/TreeManagerIndexViewModel.cs
namespace Bennington.ContentTree.TreeManager.Models
{
	public class TreeManagerIndexViewModel
	{
		public TreeNodeCreationInputModel TreeNodeCreationInputModel { get; set; }

	    public bool ContentTreeHasNodes { get; set; }
	}
}

src/Bennington.ContentTree.TreeManager/Models/TreeNodeCreationInputModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace Bennington.ContentTree.TreeManager.Models
{
	public class TreeNodeCreationInputModel
	{
		[HiddenInput(DisplayValue = false)]
		public string ParentTreeNodeId { get; set; }
		
		[DisplayName("Type")]
		[UIHint("ProviderTypes")]
		public string ProviderType { get; set; }
	}
}

src/Bennington.ContentTree.TreeManager/Controllers/TreeManagerController.cs
using System.Web.Mvc;
using Bennington.Cms.Attributes;
using Bennington.ContentTree.TreeManager.Models;
using Bennington.ContentTree.TreeManager.ViewModelBuilders;

namespace Bennington.ContentTree.TreeManager.Controllers
{
	public class TreeManagerController : Controller
	{
		private readonly ITreeBranchViewModelBuilder treeBranchViewModelBuilder;
        private readonly ITreeManagerIndexViewModelBuilder treeManagerIndexViewModelBuilder;

        public TreeManagerController(ITreeBranchViewModelBuilder treeBranchViewModelBuilder,
                                    ITreeManagerIndexViewModelBuilder treeManagerIndexViewModelBuilder)
        {
            this.treeManagerIndexViewModelBuilder = treeManagerIndexViewModelBuilder;
            this.treeBranchViewModelBuilder = treeBranchViewModelBuilder;
        }

        [Authorize]
		public virtual ActionResult Index()
		{
			return View("Index", treeManagerIndexViewModelBuilder.BuildViewModel());
		}

		[Authorize]
        [Bennington.Cms.Attributes.DoNotUseTheDefaultMasterPage]
        public virtual ActionResult Branch(string id)
		{
			return View("Branch", "Blank", treeBranchViewModelBuilder.BuildViewModel(id));
		}
	}
}

src/Bennington.ContentTree.TreeManager/Views/TreeManager/Branch.cshtml
@using Bennington.ContentTree.Models
@{ Layout = "~/Views/Shared/Blank.cshtml"; }
@model Bennington.ContentTree.TreeManager.Models.TreeBranchViewModel
    
	@foreach (var treeNode in Model.TreeNodeSummaries) {
		<li id="@treeNode.TreeNodeSummary.Id" class="@(treeNode.TreeNodeSummary.HasChildren ? "jstree-closed" : string.Empty)">
            <span class="name"><a href="@Url.Action(treeNode.TreeNodeSummary.ActionToUseForModification, treeNode.TreeNodeSummary.ControllerToUseForModification, treeNode.TreeNodeSummary.RouteValuesForModification)"><img src="@Url.Content("~")@treeNode.TreeNodeSummary.IconUrl" alt="@treeNode.TreeNodeSummary.Name" />@treeNode.TreeNodeSummary.Name</a></span>
            <span class="tree-meta">
                <span class="tools">
			        <span class="noicon">
				        <a href="#TB_inline?height=155&width=300&inlineId=createFormContainer&modal=false" class="thickbox" onclick="$('#TreeNodeCreationInputModel_ParentTreeNodeId').val('@treeNode.TreeNodeSummary.Id');$('#createInRootLink').click();"><img src="@Url.Content("~/Content/TreeManager/PlusSign.gif")" alt="Create a child" /></a>
			        </span>                
                </span>
                <span class="last-updated-date">@treeNode.TreeNodeSummary.LastModifyDate</span>
                <span class="last-updated-by">@(treeNode.TreeNodeSummary.LastModifyBy ?? "Unknown")</span>
                <span class="active">@(treeNode.TreeNodeSummary.Active ? "Active" : "Inactive")</span>
            </span>
		</li>
	}

src/Bennington.ContentTree.TreeManager/Views/TreeManager/Index.cshtml
@using System.Web.Mvc.Html
@using Bennington.ContentTree
@using Bennington.ContentTree.Models
@using System.Security.Policy
@using System.Web.Mvc
@{ Layout = "~/Views/Shared/ManageSite.cshtml"; }
@model Bennington.ContentTree.TreeManager.Models.TreeManagerIndexViewModel

@section title{
    Content Tree Management
}

@section head {

    <link href="@Url.Content("~/Content/TreeManager/JSTree/Style.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/TreeManager/jquery-1.6.4.min.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/TreeManager/jquery-ui.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/TreeManager/jquery.cookie.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/TreeManager/jquery.jstree.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/TreeManager/thickbox-compressed.js")"></script>

	<script type="text/javascript">
		$(document).ready(function () {

			$(".contentTree").jstree({
				"html_data": {
					"ajax": {
						"url": "@Url.Action("Branch", "TreeManager")",
						"data": function (n) {
							return { id: n.attr ? n.attr("id") : '@Constants.RootNodeId' };
						}
					}
				},
				"plugins": ["themes", "html_data", "cookies"]
			});

			$("#TreeNodeCreationInputModel_ProviderType").change(function () {
				var selected = $("#TreeNodeCreationInputModel_ProviderType option:selected");
				if (selected.val() != "") {
					document.forms[0].action = $("#TreeNodeCreationInputModel_ProviderType").val();
				}
			});
		});
	</script>
}
    
    <div id="pageheader" class="clearfix" style="padding-top:50px;"></div>

    <div id="tab1" class="tabContent">
        <div class="section">
            <div class="createFormContainer" id="createFormContainer" style="display:none">
				@using (Html.BeginForm("Index", "ContentTree", FormMethod.Get, new { })) {
					@Html.EditorFor(a => a.TreeNodeCreationInputModel)
					<input type="button" class="button" value="Create" onclick="if ($('#TreeNodeCreationInputModel_ProviderType').val() != '') {window.location=$('#TreeNodeCreationInputModel_ProviderType').val() + '&parentTreeNodeId=' + $('#TreeNodeCreationInputModel_ParentTreeNodeId').val();} else { alert('Please choose a type'); }" />
				}
			</div>
			<div class="contentTreeContainer clearfix">
                @if (Model.ContentTreeHasNodes)
                {
                    <div class="contentTree">
                    </div>
                } else
                {
                    <span class="noContentTree">There is no content to manage right now.  Try creating something.</span>
                }
            </div>
        </div>

		<br />
		<a id="createInRootLink" href="#TB_inline?height=155&width=300&inlineId=createFormContainer&modal=false" class="thickbox" title="Create a Node:" ><input type="button" value="Create" class="button"/></a>
		
    </div>

    <div id="tab2" class="tabContent">
    </div>